'use strict';

export const CURRENT_USER = 'CURRENT_USER';
export const CURRENT_USER_SUCCEEDED = "CURRENT_USER_SUCCEEDED";
export const CURRENT_USER_FAILED = "CURRENT_USER_FAILED";

export const LOGIN_GOOGLE = "LOGIN_GOOGLE";
export const LOGIN_GOOGLE_SUCCEEDED = "LOGIN_GOOGLE_SUCCEEDED";
export const LOGIN_GOOGLE_FAILED = "LOGIN_GOOGLE_FAILED";

export const LOGOUT_GOOGLE = "LOGOUT_GOOGLE";
export const LOGOUT_GOOGLE_SUCCEEDED = "LOGOUT_GOOGLE_SUCCEEDED";
export const LOGOUT_GOOGLE_FAILED = "LOGOUT_GOOGLE_FAILED";
